groups/urls.py
from django.urls import path
from .views import *

app_name = 'groups'

urlpatterns = [
    path('my_groups/', my_groups, name='my_groups'),
    path('group_detail/<int:group_id>/', group_detail, name='group_detail'),
    path('group_list/', group_list, name='group_list'),
    path('group_create/', group_create, name='group_create'),
    path('join_group/<int:group_id>/', join_group, name='join_group'),
    #검색 기능 뷰 추가
    path('search/', search, name='search'),
    # 10:25추가
    path('my_group_detail/<int:group_id>/', mygroup_detail, name = 'my_group_detail'),
]

groups/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
from .models import Group, Membership
from django.contrib.auth.decorators import login_required
from users.models import Profile
from django.db.models import Count
from django.utils import timezone

# 내 그룹보기
@login_required
def my_groups(request):
    profile = Profile.objects.get(user=request.user)
    memberships = Membership.objects.filter(profile=profile)
    groups = [membership.group for membership in memberships]
    return render(request, 'groups/my_groups.html', {'groups': groups})

# 전체 그룹 리스트
def group_list(request):
    groups = Group.objects.all()

    # 정렬기능 추가
    sort_by = request.GET.get('sort_by', 'created_at')

    if sort_by == '최신순':
        groups = Group.objects.all().order_by('created_at')  # 최신순
    elif sort_by == '오래된순':
        groups = Group.objects.all().order_by('-created_at')  # 오래된순
    elif sort_by == '다인원순':
        groups = Group.objects.all().order_by('-max_members')  # 다인원순
    elif sort_by == '소인원순':
        groups = Group.objects.all().order_by('max_members')  # 소인원순
    else:
        groups = Group.objects.all()  # 기본값으로 아순 정렬도 하지 않음

    return render(request, 'groups/group_list.html', {
        
        'groups': groups,
        'sort_by' : sort_by,
        })

# 그룹 상세보기 >> 여기서 가입하면 mygroup에 추가됨
def group_detail(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    user = Profile.objects.get(user=request.user)
    is_member = False

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
        is_member = group.memberships.filter(id=profile.id).exists()

    members = group.memberships.all()
    member_usernames = [membership.profile.user.username for membership in members]

    context = {
        'group':group,
        'is_member':is_member,
        'author':group.author.username,
        'created_at':group.created_at.strftime('%Y.%m.%d'),
        'member_usernames':member_usernames,
    }
    return render(request, 'groups/group_detail.html', context)

# 그룹 가입하기
@login_required
def join_group(request, group_id):
    group = get_object_or_404(Group, id = group_id)
    profile = get_object_or_404(Profile, user = request.user)
    if group.memberships.count() < group.max_members:
        Membership.objects.get_or_create(profile=profile, group=group)
    return redirect('groups:my_groups')

# 그룹 만들기
def group_create(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid(): 
            group = form.save(commit=False)
            group.author = request.user
            group.save()
            return redirect('groups:group_list')
    else:
        form = GroupForm()
    now = timezone.localtime(timezone.now())
    context = {
        'form': form,
        'current_time': now.strftime('%Y.%m.%d'),  # 현재 시간 표시
        'author': request.user.username,  # 현재 사용자 이름 표시
    }
    return render(request, 'groups/group_create.html', context)

#검색 기능 뷰 추가
@login_required
def search(request):
    search = request.GET.get('search','')
    groups = Group.objects.filter(name__icontains=search) if search else []
    return render(request, 'groups/search_list.html', {
        'groups' : groups,
        'search' : search
    })

# 나의 그룹 >> 그룹디테일
def mygroup_detail(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    user = Profile.objects.get(user=request.user)
    is_member = False

    if request.user.is_authenticated:
        profile = Profile.objects.get(user=request.user)
        is_member = group.memberships.filter(id=profile.id).exists()

    members = group.memberships.all()
    member_usernames = [membership.profile.user.username for membership in members]

    context = {
        'group':group,
        'is_member':is_member,
        'author':group.author.username,
        'created_at':group.created_at.strftime('%Y.%m.%d'),
        'member_usernames':member_usernames,
    }
    return render(request, 'groups/my_group_detail.html', context)

groups/templates/groups/group_create.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <!-- css 파일 불러오기 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/group_made.css' %}" />
    <title>group_made_page</title>
    <style>
      body {
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        min-height: 100vh;
        background-color: #efefef;
      }

      article {
        width: 430px;
        height: 932px;
        background-color: #191919;
        border-radius: 10px;
        position: relative;
        top: 0;
        left: 0;
      }
    </style>
  </head>
  <body>
    <article>
      <header>
        <a href="{% url 'main:main' %}">
          <div class="logo">
            <img src="{% static 'img/base.html_logo.svg' %}" alt="로고이미지" />
          </div>
        </a>
        <div class="title_line">
          <div class="title">그룹 만들기</div>
        </div>
      </header>
      <section>
        <div class="main">
          <form method="post">
            {% csrf_token %}
            <div class="box">
              <div class="input_title">그룹 생성일</div>
              <div class="fix_box">{{ current_time }}</div>
            </div>
            <div class="box">
              <div class="input_title">그룹 대표</div>
              <div class="fix_box">{{ author }}</div>
            </div>
            <div class="box">
              <div class="input_title">그룹 이름</div>
              <div class="input_box">{{ form.name }}</div>
            </div>
            <div class="group-select">
              <p>최대인원설정</p>
              <div class="custom-select">{{ form.max_members }}</div>
            </div>
            <div class="box">
              <div class="input_title">그룹 한 줄 소개</div>
              <div class="input_box">{{ form.introduce }}</div>
            </div>
            <div class="button_line">
              <a href="{% url 'groups:group_list' %}"><button type="submit" class="complete">생성</button></a>
            </div>
          </form>
        </div>
      </section>
      <footer>
        <div class="button_box">
          <a href="{% url 'main:main' %}">
            <button id="home"><img src="{% static 'img/base.html_home.svg' %}" alt="홈화면" /></button>
          </a>
          <a href="{% url 'groups:my_groups' %}">
            <button id="group"><img src="{% static 'img/base.html_group_active.svg' %}" alt="그룹" /></button>
          </a>
          <a href="{% url 'main:notifications' %}">
            <button id="ball"><img src="{% static 'img/base.html_ball.svg' %}" alt="알림" /></button>
          </a>
          <a href="{% url 'accounts:mypage' %}">
            <button id="mypage"><img src="{% static 'img/base.html_mypage.svg' %}" alt="마이페이지" /></button>
          </a>
        </div>
      </footer>
    </article>
    <script src="./js/group_search.js"></script>
  </body>
</html>

groups/templates/groups/group_detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <!-- css 파일 불러오기 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/group_detail.css' %}" />
    <title>group_made_page</title>
    <style>
      body {
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        min-height: 100vh;
        background-color: #efefef;
      }

      article {
        width: 430px;
        height: 932px;
        background-color: #191919;
        border-radius: 10px;
        position: relative;
        top: 0;
        left: 0;
      }
    </style>
  </head>
  <body>
    <article>
      <div class="detail_box">
        <div class="title">{{ group.name }}</div>
        <div class="info">
          <div class="info_1">{{created_at}}</div>
          <div class="info_2"><span>인원</span>{{group.memberships.count}}/{{ group.max_members }}명<span>그룹장</span>{{author}}</div>
          <div class="intro">{{ group.introduce }}</div>
        </div>
        <div class="member">
          {% for username in member_usernames %}
          <div class="nickname">{{ username }}</div>
          {% endfor %}
      </div>
        <div class="select_line">
          <a href="{% url 'groups:join_group' group.id %}"><button class="join">그룹가입</button></a>
          <a href="{% url 'groups:group_list' %}"><button class="cancel">취소</button></a>
        </div>
      </div>
    </article>
    <script src="{% static 'js/group_search.js' %}"></script>
  </body>
</html>

groups/templates/groups/group_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/group_search.css' %}" />
    <title>group_search_page</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: flex-start;
            align-items: flex-start;
            min-height: 100vh;
            background-color: #efefef;
        }

        article {
            width: 430px;
            height: 932px;
            background-color: #191919;
            border-radius: 10px;
            position: relative;
            top: 0;
            left: 0;
        }
    </style>
</head>
<body>
    <article>
        <header>
            <a href="{% url 'main:main' %}">
                <div class="logo">
                    <img src="{% static 'img/base.html_logo.svg' %}" alt="로고이미지" />
                </div>
            </a>
            <div class="title_line">
                <div class="title">그룹 찾기</div>
            </div>
        </header>
        <section>
            <div class="search_box">
                <form method="GET" action="{% url 'groups:search' %}">
                    <input type="text" name="search" value="{{ search }}" placeholder="그룹명으로 검색" />
                    <input type="hidden" name="sort_by" id="sort_by_input" value="{{ sort_by }}">
                    <button type="submit">
                        <img src="{% static 'img/group_search.html_search.svg' %}" alt="검색아이콘" />
                    </button>
                </form>
            </div>
            <div class="group-select">
                <p>정렬기준</p>
                <div class="sort">
                  <form method="GET" action="{% url 'groups:group_list' %}">
                      <select name="sort_by" onchange="this.form.submit()">
                          <option value="최신순" {% if sort_by == '최신순' %}selected{% endif %}>최신순</option>
                          <option value="오래된순" {% if sort_by == '오래된순' %}selected{% endif %}>오래된순</option>
                          <option value="다인원순" {% if sort_by == '다인원순' %}selected{% endif %}>다인원순</option>
                          <option value="소인원순" {% if sort_by == '소인원순' %}selected{% endif %}>소인원순</option>
                      </select>
                  </form>
              </div>
            </div>
            <div class="team_list">
                {% if groups %}
                    {% for group in groups %}
                    <a href="{% url 'groups:group_detail' group.id %}">
                        <div class="team_box">
                            <div class="team_name">{{ group.name }}</div>
                            <div class="team_info">
                                <div class="info_1"><span>인원</span>{{group.memberships.count}}/{{ group.max_members }}명</div>
                                <div class="info_2"><span>그룹장</span>{{ group.author }}</div>
                                <div class="info_3"><span>시작일</span>{{ group.created_at|date:"Y.m.d" }}</div>
                            </div>
                            <div class="team_intro">{{ group.introduce }}</div>
                        </div>
                    </a>
                    {% endfor %}
                {% else %}
                    <p>검색결과가 없습니다.</p>
                {% endif %}
            </div>
            <a href="{% url 'groups:group_create' %}">
                <div class="add_button">
                    <img src="{% static 'img/group_main.html_+button.svg' %}" alt="추가버튼" />
                </div>
            </a>
        </section>
        <footer>
            <div class="button_box">
              <a href="{% url 'main:main' %}">
                <button id="home"><img src="{% static 'img/base.html_home.svg' %}" alt="홈화면" /></button>
              </a>
              <a href="{% url 'groups:my_groups' %}">
                <button id="group"><img src="{% static 'img/base.html_group_active.svg' %}" alt="그룹" /></button>
              </a>
              <a href="{% url 'main:notifications' %}">
                <button id="ball"><img src="{% static 'img/base.html_ball.svg' %}" alt="알림" /></button>
              </a>
              <a href="{% url 'accounts:mypage' %}">
                <button id="mypage"><img src="{% static 'img/base.html_mypage.svg' %}" alt="마이페이지" /></button>
              </a>
            </div>
          </footer>
    </article>
    <script src="{% static 'js/group_search.js' %}"></script>
    <script>
        function setSortBy(value) {
            document.getElementById('sort_by_input').value = value;
            document.querySelector('form').submit();
        }

        // 커스텀 셀렉트 박스 스크립트
        var x, i, j, selElmnt, a, b, c;
        x = document.getElementsByClassName("custom-select");
        for (i = 0; i < x.length; i++) {
            selElmnt = x[i].getElementsByTagName("select")[0];
            a = document.createElement("DIV");
            a.setAttribute("class", "select-selected");
            a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
            x[i].appendChild(a);
            b = document.createElement("DIV");
            b.setAttribute("class", "select-items select-hide");
            for (j = 0; j < selElmnt.length; j++) {
                c = document.createElement("DIV");
                c.innerHTML = selElmnt.options[j].innerHTML;
                c.addEventListener("click", function(e) {
                    var y, i, k, s, h;
                    s = this.parentNode.parentNode.getElementsByTagName("select")[0];
                    h = this.parentNode.previousSibling;
                    for (i = 0; i < s.length; i++) {
                        if (s.options[i].innerHTML == this.innerHTML) {
                            s.selectedIndex = i;
                            h.innerHTML = this.innerHTML;
                            y = this.parentNode.getElementsByClassName("same-as-selected");
                            for (k = 0; k < y.length; k++) {
                                y[k].removeAttribute("class");
                            }
                            this.setAttribute("class", "same-as-selected");
                            break;
                        }
                    }
                    h.click();
                });
                b.appendChild(c);
            }
            x[i].appendChild(b);
            a.addEventListener("click", function(e) {
                e.stopPropagation();
                closeAllSelect(this);
                this.nextSibling.classList.toggle("select-hide");
                this.classList.toggle("select-arrow-active");
            });
        }
        function closeAllSelect(elmnt) {
            var x, y, i, arrNo = [];
            x = document.getElementsByClassName("select-items");
            y = document.getElementsByClassName("select-selected");
            for (i = 0; i < y.length; i++) {
                if (elmnt == y[i]) {
                    arrNo.push(i)
                } else {
                    y[i].classList.remove("select-arrow-active");
                }
            }
            for (i = 0; i < x.length; i++) {
                if (arrNo.indexOf(i)) {
                    x[i].classList.add("select-hide");
                }
            }
        }
        document.addEventListener("click", closeAllSelect);
    </script>
</body>
</html>

groups/templates/groups/my_group_detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <!-- css 파일 불러오기 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/group_detail.css' %}" />
    <title>group_made_page</title>
    <style>
      body {
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        min-height: 100vh;
        background-color: #efefef;
      }

      article {
        width: 430px;
        height: 1000px;
        background-color: #191919;
        border-radius: 10px;
        position: relative;
        top: 0;
        left: 0;
      }
    </style>
  </head>
  <body>
    <article>
      <div class="detail_box">
        <div class="title">{{ group.name }}</div>
        <div class="info">
          <div class="info_1">{{created_at}}</div>
          <div class="info_2"><span>인원</span>{{group.memberships.count}}/{{ group.max_members }}명<span>그룹장</span>{{author}}</div>
          <div class="intro">{{ group.introduce }}</div>
        </div>
        <div class="member">
          {% for username in member_usernames %}
          <div class="nickname">{{ username }}</div>
          {% endfor %}
      </div>
        <div class="select_line">
          <a href="{% url 'main:main' %}"><button class="cancel">취소</button></a>
        </div>
      </div>
    </article>
    <script src="{% static 'js/group_search.js' %}"></script>
  </body>
</html>

groups/templates/groups/my_groups.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <!-- css 파일 불러오기 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/group_main.css' %}" />
    <title>group_main_page</title>
    <style>
      body {
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
        min-height: 100vh;
        background-color: #efefef;
      }

      article {
        width: 430px;
        height: 932px;
        background-color: #191919;
        border-radius: 10px;
        position: relative;
        top: 0;
        left: 0;
      }
    </style>
  </head>
  <body>
    <article>
      <header>
        <a href="{% url 'main:main' %}">
          <div class="logo">
            <img src="{% static 'img/base.html_logo.svg' %}" alt="로고이미지" />
          </div>
        </a>
        <div class="title_line">
          <div class="title">나의 그룹</div>
        </div>
      </header>
      <section>
        {% for group in groups %}
        <a href="{% url 'groups:my_group_detail' group.id %}">
          <div class="team_box">
            <div class="team_name">{{ group.name }}</div>
            <div class="team_info">
              <div class="info_1"><span>인원</span>{{group.memberships.count}}/{{ group.max_members }}명</div>
              <div class="info_2"><span>그룹장</span>{{ group.author }}</div>
              <div class="info_3"><span>시작일</span>{{ group.created_at|date:"Y.m.d" }}</div>
            </div>
            <div class="team_intro">{{ group.introduce }}</div>
          </div>
        </a>
        {% empty %}
        <div class="notice">
          <div class="text">가입한 그룹이 없습니다.</div>
          <div class="text"><span>+버튼</span>을 눌러 <span>메세지 그룹을 추가</span>해보세요.</div>
        </div>
        {% endfor %}
        <a href="{% url 'groups:group_list' %}">
          <div class="add_button">
            <img src="{% static 'img/group_main.html_+button.svg' %}" alt="추가버튼" />
          </div>
        </a>
      </section>
      <footer>
        <div class="button_box">
          <a href="{% url 'main:main' %}">
            <button id="home"><img src="{% static 'img/base.html_home.svg' %}" alt="홈화면" /></button>
          </a>
          <a href="{% url 'groups:my_groups' %}">
            <button id="group"><img src="{% static 'img/base.html_group_active.svg' %}" alt="그룹" /></button>
          </a>
          <a href="{% url 'main:notifications' %}">
            <button id="ball"><img src="{% static 'img/base.html_ball.svg' %}" alt="알림" /></button>
          </a>
          <a href="{% url 'accounts:mypage' %}">
            <button id="mypage"><img src="{% static 'img/base.html_mypage.svg' %}" alt="마이페이지" /></button>
          </a>
        </div>
      </footer>
    </article>
    <script>
      document.addEventListener("DOMContentLoaded", () => {
        const buttons = document.querySelectorAll(".button_box button");
        buttons.forEach((button) => {
          button.addEventListener("click", () => {
            buttons.forEach((btn) => {
              btn.classList.remove("active");
              const img = btn.querySelector("img");
              const imgSrc = img.getAttribute("src").replace("_active", "");
              img.setAttribute("src", imgSrc);
            });
            button.classList.add("active");
            const img = button.querySelector("img");
            const imgSrc = img.getAttribute("src").replace(".svg", "_active.svg");
            img.setAttribute("src", imgSrc);
          });
        });
      });
    </script>
  </body>
</html>

groups/templates/groups/search_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>search_list_page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/group_search.css' %}" />
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: flex-start;
            align-items: flex-start;
            min-height: 100vh;
            background-color: #efefef;
        }

        article {
            width: 430px;
            height: 932px;
            background-color: #191919;
            border-radius: 10px;
            position: relative;
            top: 0;
            left: 0;
        }
    </style>
</head>
<body>
    <article>
        <header>
            <a href="{% url 'main:main' %}">
                <div class="logo">
                    <img src="{% static 'img/base.html_logo.svg' %}" alt="로고이미지" />
                </div>
            </a>
            <div class="title_line">
                <div class="title">그룹 찾기</div>
            </div>
        </header>
        <section>
            <div class="search_box">
                <form method="GET" action="{% url 'groups:search' %}">
                    <input type="text" name="search" value="{{ search }}" placeholder="그룹명으로 검색" />
                    <input type="hidden" name="sort_by" id="sort_by_input" value="{{ sort_by }}">
                    <button type="submit">
                        <img src="{% static 'img/group_search.html_search.svg' %}" alt="검색아이콘" />
                    </button>
                </form>
            </div>
            <div class="group-select">
                <p>정렬기준</p>
                <div class="sort">
                    <form method="GET" action="{% url 'groups:search' %}">
                        <input type="hidden" name="search" value="{{ search }}">
                        <select name="sort_by" onchange="this.form.submit()">
                            <option value="최신순" {% if sort_by == '최신순' %}selected{% endif %}>최신순</option>
                            <option value="오래된순" {% if sort_by == '오래된순' %}selected{% endif %}>오래된순</option>
                            <option value="다인원순" {% if sort_by == '다인원순' %}selected{% endif %}>다인원순</option>
                            <option value="소인원순" {% if sort_by == '소인원순' %}selected{% endif %}>소인원순</option>
                        </select>
                    </form>
                </div>
            </div>
            <div class="team_list">
                {% if groups %}
                    {% for group in groups %}
                    <a href="{% url 'groups:group_detail' group.id %}">
                        <div class="team_box">
                            <div class="team_name">{{ group.name }}</div>
                            <div class="team_info">
                                <div class="info_1"><span>인원</span>{{group.memberships.count}}/{{ group.max_members }}명</div>
                                <div class="info_2"><span>그룹장</span>{{ group.author }}</div>
                                <div class="info_3"><span>시작일</span>{{ group.created_at|date:"Y.m.d" }}</div>
                            </div>
                            <div class="team_intro">{{ group.introduce }}</div>
                        </div>
                    </a>
                    {% endfor %}
                {% else %}
                    <p>검색결과가 없습니다.</p>
                {% endif %}
            </div>
            <a href="{% url 'groups:group_create' %}">
                <div class="add_button">
                    <img src="{% static 'img/group_main.html_+button.svg' %}" alt="추가버튼" />
                </div>
            </a>
        </section>
        <footer>
            <div class="button_box">
              <a href="{% url 'main:main' %}">
                <button id="home"><img src="{% static 'img/base.html_home.svg' %}" alt="홈화면" /></button>
              </a>
              <a href="{% url 'groups:my_groups' %}">
                <button id="group"><img src="{% static 'img/base.html_group_active.svg' %}" alt="그룹" /></button>
              </a>
              <a href="{% url 'main:notifications' %}">
                <button id="ball"><img src="{% static 'img/base.html_ball.svg' %}" alt="알림" /></button>
              </a>
              <a href="{% url 'accounts:mypage' %}">
                <button id="mypage"><img src="{% static 'img/base.html_mypage.svg' %}" alt="마이페이지" /></button>
              </a>
            </div>
          </footer>
    </article>
    <script src="{% static 'js/group_search.js' %}"></script>
    <script>
        function setSortBy(value) {
            document.getElementById('sort_by_input').value = value;
            document.querySelector('form').submit();
        }

        // 커스텀 셀렉트 박스 스크립트
        var x, i, j, selElmnt, a, b, c;
        x = document.getElementsByClassName("custom-select");
        for (i = 0; i < x.length; i++) {
            selElmnt = x[i].getElementsByTagName("select")[0];
            a = document.createElement("DIV");
            a.setAttribute("class", "select-selected");
            a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
            x[i].appendChild(a);
            b = document.createElement("DIV");
            b.setAttribute("class", "select-items select-hide");
            for (j = 0; j < selElmnt.length; j++) {
                c = document.createElement("DIV");
                c.innerHTML = selElmnt.options[j].innerHTML;
                c.addEventListener("click", function(e) {
                    var y, i, k, s, h;
                    s = this.parentNode.parentNode.getElementsByTagName("select")[0];
                    h = this.parentNode.previousSibling;
                    for (i = 0; i < s.length; i++) {
                        if (s.options[i].innerHTML == this.innerHTML) {
                            s.selectedIndex = i;
                            h.innerHTML = this.innerHTML;
                            y = this.parentNode.getElementsByClassName("same-as-selected");
                            for (k = 0; k < y.length; k++) {
                                y[k].removeAttribute("class");
                            }
                            this.setAttribute("class", "same-as-selected");
                            break;
                        }
                    }
                    h.click();
                });
                b.appendChild(c);
            }
            x[i].appendChild(b);
            a.addEventListener("click", function(e) {
                e.stopPropagation();
                closeAllSelect(this);
                this.nextSibling.classList.toggle("select-hide");
                this.classList.toggle("select-arrow-active");
            });
        }
        function closeAllSelect(elmnt) {
            var x, y, i, arrNo = [];
            x = document.getElementsByClassName("select-items");
            y = document.getElementsByClassName("select-selected");
            for (i = 0; i < y.length; i++) {
                if (elmnt == y[i]) {
                    arrNo.push(i)
                } else {
                    y[i].classList.remove("select-arrow-active");
                }
            }
            for (i = 0; i < x.length; i++) {
                if (arrNo.indexOf(i)) {
                    x[i].classList.add("select-hide");
                }
            }
        }
        document.addEventListener("click", closeAllSelect);
    </script>
</body>
</html>